// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbKjnRRQYGW78O9waWEO5-CHbo6IU7D8k',
    appId: '1:474983529837:web:84a36893035b482fb1ae64',
    messagingSenderId: '474983529837',
    projectId: 'datn-d516a',
    authDomain: 'datn-d516a.firebaseapp.com',
    storageBucket: 'datn-d516a.appspot.com',
    measurementId: 'G-B5VJSZGD41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDSGnfQqfE58r4XScYq8HF-HCBVqIqwK4',
    appId: '1:474983529837:android:7b58d80cbfee9589b1ae64',
    messagingSenderId: '474983529837',
    projectId: 'datn-d516a',
    storageBucket: 'datn-d516a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUPs_0hPtXW0oqKi3T1mSqk_IgvuYITyQ',
    appId: '1:474983529837:ios:ec3da3ec6c398c7cb1ae64',
    messagingSenderId: '474983529837',
    projectId: 'datn-d516a',
    storageBucket: 'datn-d516a.appspot.com',
    iosBundleId: 'com.example.expenditureManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUPs_0hPtXW0oqKi3T1mSqk_IgvuYITyQ',
    appId: '1:474983529837:ios:ec3da3ec6c398c7cb1ae64',
    messagingSenderId: '474983529837',
    projectId: 'datn-d516a',
    storageBucket: 'datn-d516a.appspot.com',
    iosBundleId: 'com.example.expenditureManagement',
  );
}
